version: 'latest'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - mqtt_net

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    # enviroment:
		# 	- ME_CONFIG_MONGODB_ADMINUSERNAME=admin
		# 	- ME_CONFIG_MONGODB_ADMINPASSWORD=password
		# 	- ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - mqtt_net

networks:
  mqtt_net:
    driver: bridge
